### PR TITLE
[BOARD] add flashing procedure to firstboot + disclaimer msg

### PR DESCRIPTION
**Pull request by Apaczer**
# FLASHING configuration
## License agrrement message at first booting
This apply to all devices, launching with 30s timeout and the user need to navigate to "YES" selection or the ``poweroff`` commences.
If he can't select YES it means: he either dissagre with the terms or don't have working keyboard or screen to make proper selection.
system-8

## Selection MENU for ST7789S screen family devices
<ins>Displays under 2 conditions:<ins>
- if there is no specifc CONSOLE_VARIANT specified in console.cfg
  &&
- if  uboot detects ST7789S display
system-10
system-6

For rest of devices with different display controller the uboot autodetection should handel them properly. However BittBoys may need another treatment, because for now there is no other way than forcing correct version in console.cfg.

### CODE REVIEW

**Comment by TriForceX** [comment]
Nice! i was just going to ask about the selection of console variants a few weeks ago when you added the resize partition option! that seems excellent! what is the possibility of adding all the variants in the same dialog from now, and list the auto-detected ones with (recommended) in the name? or maybe show them all and in an new line the recommended ones? (idk if im explaining myself properly)

**Comment by Apaczer** [comment]
Yup that was my initial thought to include all in one list, but came into realization it make no sense if autodetection do most of this stuff for other variants. 
Example: you have SUP M3 but you write ``pocketgo`` in console.cfg, then **u-boot** regardless of your bad choice will force to boot with correct variant (the screen determines other module.parameters like miyoo.keyboard variant at such scenario). There are a few exceptions like BittBoy and M3 with gc9306fb (need to specify variant otherwise bad input mapping/GPIO read may occure).

<ins>What I could do next is to maybe:<ins>
- display prompt with autodetected device to inform user of such thing if no selection menu is needed.
- show testing msgbox "Does your buttons work correctly: select YES/NO" if NO after timeout, then change variant, reboot and perform again that test until finding right one mapping. Mostly for Bittboys.

If everything goes well, the enduser will not have to specify variant in console.cfg at all.

**Comment by Apaczer** [comment]
Well I think we should try:
* for Bittboys (ST7789S controller):
  - "Does your buttons work correctly?" YES/NO; reboot; correct
  - "Is your display upsided-down?" YES/NO ; reboot ; correct
  - "License"
  - "Your device: ..."
  - end

* for XYC/M3 (other controllers):
  - "Does your buttons work correctly?" YES/NO; reboot; correct
  - "Are your colors inverted?" YES/NO ; reboot ; correct
  - "Licence"
  - "Your device: ..."
  - end
  

@tiopex is there difference between bittboy2x_v1 and bittboy2x_v2 just beside using different fb driver? - they seem to use the same ST7789 controller?

**Comment by tiopex** [comment]
v1 use r61520, v2 st7789, both have same device id (st7789)

**Comment by Apaczer** [comment]
so v1 and v2 will not work on the same device? This might be a problem then.

**Comment by Apaczer** [comment]
For ST7789S family we have additional message:
system-1

If "No" image that means we have Bittboyx2_v1 (bittboy) with other video controller

If the user chose "Flipped" it means we have either Bittboyx2_v2 (bittboy2) or bittboy3.5 (bittboy3).
We need to check if proper button inputs has been set:
system-3

Finally show "LICENSE" msgbox & we can enjoy our device.

Below there is time counter from --pause option.

**Comment by Apaczer** [comment]
Using new "bittboy" "bittboy2" "bittboy3" from DETECTED_VERSION in https://github.com/MiyooCFW/uboot/pull/21

If smbd want to bypass this whole process, he/she needs only to write one of FORCE_VERSION in console.cfg but firstly we'll have to merge above PR.

Next will add XYC/M3 to the flash procedure pool

**Comment by Apaczer** [comment]
This is my final sketch of the whole "Flashing Procedure" in this PR, you can display/modify it in draw.io:
<ins> EDIT: 2023-06-24 10:12 (UTC +02:00) <ins>

flashing_v11 drawio

**Comment by tiopex** [comment]
I suppose that option No in "Can you see this message has timeout. So in that case, the loop should back to default state e.g.

On-> can you see? -> no -> console=bittboy -> reboot -> can you see? -> no -> console=unknown -> reboot

**Comment by Apaczer** [comment]
Updated diagram, cuz there is no loop in fact at this point (sry!). After setting variant to "bittboy" (first block) then automaticly forced "bittboy2x_v1" (second block), we arrive to last LICENSE msgbox where after timeout it sets to "unknown" variant and poweroffs.
Possibly I could just redo "Test_Video" test for that forced variant, but on the other hand it will expand whole script on second block (not sure yet).

**Comment by TriForceX** [comment]
@Apaczer im at phone right now, cant do a new test right now, but 2 days ago ive installed this version on a v90 for a friend, in the install process after the "buttons and upsidedown" question and the resize feature passed successfully it said "your device" and showed Bittboy 3.5, i wasnt able to do/check anything because the screen dissapeared very fast (after 2 or 3 seconds) and then it got restarted and everything got configured for bittboy 3.5, so i had to change the stuff manually after that.

Is there anything i should consider or check for new tests about this?

**Comment by Apaczer** [comment]
> Is there anything i should consider or check for new tests about this?

Firstly flash u-boot from this PR build: https://github.com/MiyooCFW/uboot/actions/runs/5271803450 (use firstboot.custom.sh)

However in your case I believe you might have selected unintentionally _"Flipped!"_ option at first msgbox, otherwise you wouldn't get "Test Keyboard" msgbox (look at diagram). I will add short msgbox after selection e.g _"Image Flipped! Correcting and rebooting, wait a few second"_, for more clarity.

I'll add here that default selection is _"Flipped!"_ at start for ST7789S. This is because miyoo.kbd version 1 & 2 work the same here for OK/CONFIRM key, but not for the D-PAD movement (that's why "Test Keyboard" is after "Test Video" for bittboys).

If the user thinks _"Your device: \<console\>"_ is incorrect, then don't accept LICENSE and whole flashing procedure should be canceled. Might consider adding _"Does selected device match yours?"_ yes/no dialog 🤔 

BTW Thanks for testing 🙏

**Comment by Apaczer** [comment]
Updated diagram, while adding new Test_Video'2 for "bittboy" variant on second run/block. Moreover we have Test_Variant on last block (before License) asking if correct CONSOLE_VARIANT has been set. 

_
There is nothing to do before merge but in future I have plans to:
- use special characters to make text readable upside down on first Test_Video flipped:
``` ɐqɔpǝɟƃɥᴉɾʞןɯuodbɹsʇnʌʍxʎz∀𐐒ƆᗡƎℲ⅁HIᒋ⋊ꞀWNOԀΌᴚS⊥∩ɅMX⅄Z```
```¡„#$%⅋,‘)(+,-˙/:><¿@]\\][‾,}{|~```
not possible currently on our tty console
- grep all variants from DETECTED_VERSION of uEnv in first block
- refactor Test_Image "invert" output cmd

**Pull request merged**
