### PR TITLE
[PACKAGE] Revert video sync option in retroarch, update picodrive, gpsp core

### PR DESCRIPTION
**Pull request by tiopex**
- Revert video sync option G-sync option as it disables ff function
 - update picodrive to latest
 - update gpsp to latest

### CODE REVIEW

**Comment by IDOCARE1** [comment]
Hi, I did this, and fast forward now works, but once it is turned on it won't turn off. The only way I can stop fast forward now is to go into RA frame throttle and reduce the fastforward speed to 1x, which obviously isn't really turning it off, just changing what it does.

**Comment by tiopex** [comment]
I cannot reproduce it, I checked two hotkeys, toggle and hold, and both works correctly. Could you tell more details, which core, which hotkey, button?

**Comment by IDOCARE1** [comment]
Gambatte core.

I have the fast forward (toggle) set to button 11 (r2), I set it to that button in the settings>input>retropad binds>port 1 controls.

Basically, when I press R2, the message shows in the bottom of the screen saying fast forward, and it goes away when I press it again. But the speed I set the "fast forward rate" to in "frame throttle" is the speed the game plays at, and pressing R2 doesn't change the speed.

**Comment by IDOCARE1** [comment]
So, I just tried the tv out with the gambatte core. That seems to reset the RA settings, but even when assigning the fast forward (toggle) to R1, it still functions like fastforward (hold), but does turn on and off.

I don't know what's going on there.

But when disconnected from the TV, I have fast forward set to button 11 (r2),

I set it to that button in the settings>input>retropad binds>port 1 controls
settings>input> hotkeys>fast forward (hold)
and
quick menu>controls>port 1> R (auto) is set to fast forward.

Those settings just keep it stick on fast forward, even when I press R1.

**Comment by tiopex** [comment]
I'm not able to reproduce it, works correctly for me

**Pull request merged**
