### PR TITLE
[BOARD/CONFIG] add flush option to main partition, mount root partition read-only

### PR DESCRIPTION
**Pull request by tiopex**
for unknown reasons when gmenu2x process starts, it removes 'sync' flag from mount options for /mnt partition. So as a workaround use 'flush' flag

Also add to config mount root partition read-only

### CODE REVIEW

**Comment by Apaczer** [comment]
system("mount -o remount,async /mnt") in miyoo.h header of gmenu2x. Maybe there's loading drawback with large database?

**Comment by tiopex** [comment]
> system("mount -o remount,async /mnt") in miyoo.h header of gmenu2x. Maybe there's loading drawback with large database?

Ok,we could check flush option here too

**Comment by Apaczer** [comment]
so the `flush` produce less overhead comparingly to `sync` but is more pron for data loss?

**Comment by tiopex** [comment]
> so the `flush` produce less overhead comparingly to `sync` but is more pron for data loss?

Sync - no buffer
Flush - buffer, but write on disk as soon as possible
Async - buffer as long as possible, reduce write to disk

**Comment by Apaczer** [comment]
FYI: I did not find flush option in mount(8) [optmap](https://github.com/util-linux/util-linux/blob/12f5423fc2ed08e1945fac95f3bdeb39bb915ea7/libmount/src/optmap.c#L71C9-L71C9)

**Comment by tiopex** [comment]
> FYI: I did not find flush option in mount(8) [optmap](https://github.com/util-linux/util-linux/blob/12f5423fc2ed08e1945fac95f3bdeb39bb915ea7/libmount/src/optmap.c#L71C9-L71C9)

It is related with vfat filesystem 
https://www.kernel.org/doc/Documentation/filesystems/vfat.txt

**Comment by Apaczer** [comment]
So you can mount but you can't remount with flush (from what I understand), cuz it's vfat specific settings.

**Comment by tiopex** [comment]
> So you can mount but you can't remount with flush (from what I understand), cuz it's vfat specific settings.

no, why? You can remount also with flush too

**Comment by Apaczer** [comment]
> no, why? You can remount also with flush too

Not with `remount`, maybe if you umount/mount again, but I don't see how that happens after OS running. The kernel docs' and man aren't really explaining much, from `/bin/mount` it looks like `/mnt` is running in default async with flush setting.

**Comment by Apaczer** [comment]
I sugget we go with `mount /dev/mmcblk0p4 /mnt -t vfat -o rw,sync,flush,utf8` as compromise, WDYT? Aside did you try exFAT already?

**Comment by tiopex** [comment]
> I sugget we go with `mount /dev/mmcblk0p4 /mnt -t vfat -o rw,sync,flush,utf8` as compromise, WDYT? 

Don't they exclude each other?

> Aside did you try exFAT already?

exFat is not supported by genimage.

Edit: we could use virt-make-fs but there is no resize also.

**Comment by Apaczer** [comment]
> exFat is not supported by genimage.

Yeah, smbd already issued a request on [geimage repo](https://github.com/pengutronix/genimage)

About FAT syncing, I asked Ogawa Hirofumi for some clarification:

> _FAT doesn't have the way to prevent corruption perfectly when
> abnormal shutdown._
> 
> "_The "flush" option flushes dirty buffers earlier than normal, but
> implementation is broken more or less, and not prevent the
> corruption._
> 
> _"sync" option is trying to flush dirty buffers before returning from
> each syscall, so this is the most safety option for FAT, but very slow._
> 
> _Other option would be to run "sync" command (or "sync" syscall)
> periodically in userspace._

EDIT:
I'm guessing that there's no need for `flush` when `sync` is enabled. Not sure what's broken in `flush`, but I don't yet see a reason to **NOT** use just `sync` (at least from bare testings).

**Comment by tiopex** [comment]
Another option is to use NTFS which have journaling.

But in kernel full support of NTFS is since kernel 5.15.x. Or we could use ntfs-3g fuse edriver.

 There is also possibility to resize ntfs

**Comment by Apaczer** [comment]
what about "mount root partition read-only" part

**Pull request closed without merging**
