### PR TITLE
Toolchain: bump kernel headers to 5.15.x

### LINKED ISSUE #68: [JOYMAP/musl] build broken - stderr: short write
The musl fix patch is building output binary but the app works only for a little period when launching `loadmap <map_name>` before crashing, so it can't remap joykeys correctly.

### PR DESCRIPTION
**Pull request by tiopex**
bump kernel headers to 5.15.x

fix gamepad support on musl build

### CODE REVIEW

**Comment by Apaczer** [comment]
Strange, why does it implicate default headers should 5.15 for musl (not 5.16 as kernel version). The uClibc seems normal in that manner

**Comment by tiopex** [comment]
kernel version is 5.15

**Comment by Apaczer** [comment]
meh my bad it does not implicated default headers only for static defconfigs

**Comment by Apaczer** [comment]
just as an explanation from Alexandre:
> "Short write" means that the kernel did not accept all the data that loadmap attempted to write...Since we are working with uinput (and kernel interfaces), we expect that anything we write should be accepted in its entirety. When the kernel, or libc does not accept all of it, then we end up with the short write scenario. It is possible to make it better at this, but the code will become somewhat more complex since we are trying to balance reads from input devices and writes to output devices and responding in near real time to all such events.

**Pull request merged**
