### PR TITLE
PACKAGE: Add DirectFB2 & SDL2

### PR DESCRIPTION
**Pull request by tiopex**
Add SDL2 (no opengl)  support with directFB2 as video backend

### CODE REVIEW

**Comment by Apaczer** [comment]
tested OpenJazz and seems to be running good (not demanding app), the SDL_NOMOUSE envvar looks to have been depracated in SDL2.
Nice to have backend supporting SDL2 this will allow for more ports to happen. Not sure how sdl2 handles no harwdare acceleration in runtime as it switched from pure CPU rending in favor mostly of GPU.

**Comment by tiopex** [comment]
to disable cursor add `no-cursor` to `/etc/directfbrc` file

**Comment by Apaczer** [comment]
> to disable cursor add `no-cursor` to `/etc/directfbrc` file

could be added to board/miyoo, we want it to be default setup

**Comment by tiopex** [comment]
added no-cursor, sw opengl not possible (swiftshader require at least VFP)

**Comment by Apaczer** [comment]
ARMv5 is kinda limited (no FPU,VFP, NEON...), so it's understandable. We can always defer to `portablegl` if insist

**Comment by Apaczer** [comment]
full `direcftbrc` usage help usage: https://github.com/directfb2/DirectFB2/blob/4d6b7ddd8477b4b52aa78ec82a3add28ade0c965/src/misc/conf.c#L33

**Pull request merged**
