### PR TITLE
PACKAGES: correct LICENSE_FILES

### LINKED ISSUE #111: To-Do: Check missing license files
Reference: https://github.com/MiyooCFW/buildroot/pull/110

### PR DESCRIPTION
**Pull request by Apaczer**
There are bunch of other warnings (like mising licenses), but I'm just trying to force `make legal-info` output a necessary "manifest.csv" for now.

### CODE REVIEW

**Comment by TriForceX** [comment]
Looks fine to me for now!
Anyways ive added an issue to address this at some point.

**Comment by Apaczer** [comment]
We've been missing in reality license only for [logo](https://github.com/MiyooCFW/logo), but sourted out quickly!: https://github.com/hi-ban/boot-logo/issues/1

Rest should be a plain adding path and license type in BR2 makefiles

**Comment by Apaczer** [comment]
- for hashes using util script:
https://github.com/MiyooCFW/buildroot/blob/a49827b07cc716a63440cd24c1d911a4c2614de9/utils/add-missing-hashes

- for license just GH API from terminal: 
```bash
function check_license() {    gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${1}/${2}/license;  }
```
e.g.: `$: check_license libretro retroarch`

**Comment by Apaczer** [comment]
Can't generate hashes for following pkgs (due to non-fixed version aka "master/latest"):
```
        package/miyoo/gmenu2x/gmenu2x.hash
        package/miyoo/gmenu2x-gm2xpkg/gmenu2x-gm2xpkg.hash
        package/miyoo/miyoo-ctl/miyoo-ctl.hash
        package/miyoo/miyoo-daemon/miyoo-daemon.hash
        package/miyoo/miyoo-logo/miyoo-logo.hash
```
May fix it at some point by hardcoding above pkgs' version in buildroot and just building up-to-date img only from TriForceX/MiyooCFW - I've no other idea for now and it's better as we could at least reproduce easly img build from MiyooCFW/buildroot commit hash.

**Pull request merged**
